#tipe data boolean
print(True)

#input data String
print("Ayo blejar Python")
print("Belajar Python Sangat Mudah")

#tipe data integer
print(20)

#tipe data Float
print(3.14)

#tipe data Hexadecimal
#print(9a)

#tipe data Complex
print(5j)

#tipe data list
print([1,2,3,4,5])
print(["satu","dua","tiga"])

#tipe data Tuple
print((1,2,3,4,5))
print("satu","dua","tiga")

#tipe data Dictionary
print({"nama":"Budi",'umur':20})
#tipe data Dictionary dimasukan ke dalam variabel biodata
biodata={"nama":"Andi",'umur':21} #proses inisialisasi variabel biodata
print(biodata) #proses pencetakan variabel biodata yang berisi tipe data Dictionary
print(type(biodata)) #fungsi untuk mengecek jeni stipe data akan tampil <class'diet'> yang berarti dict adalah tipe data dictionary
